CodingEvents/Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodingEvents.Models
{
    public class Event
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string ContactEmail { get; set; }
        public EventCategory Category { get; set; }
        public int CategoryId { get; set; }
        public int Id { get; set; }
        public Event()
        {
        }
        public Event(string name, string description, string contactEmail)
        {
            Name = name;
            Description = description;
            ContactEmail = contactEmail;
        }

        public override string ToString()
        {
            return Name;
        }

        public override bool Equals(object obj)
        {
            return obj is Event @event &&
                   Id == @event.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

CodingEvents/Controllers/EventsController.cs
using CodingEvents.Data;
using CodingEvents.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodingEvents.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.Tracing;
using Microsoft.AspNetCore.Authorization;

namespace CodingEvents.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private EventDbContext context;

        public EventsController(EventDbContext dbContext)
        {
            context = dbContext;
        }

        //GET: /<controller>/
        [AllowAnonymous]
        public IActionResult Index()
        {
            List<Event> events = context.Events
                .Include(e => e.Category)
                .ToList();
            return View(events);
        }

        [HttpGet]
        public IActionResult Add()
        {
            List<EventCategory> categories = context.Categories.ToList();
            AddEventViewModel addEventViewModel = new AddEventViewModel(categories);
            return View(addEventViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddEventViewModel addEventViewModel)
        {
            if (ModelState.IsValid)
            {
                EventCategory theCategory = context.Categories.Find(addEventViewModel.CategoryId);
                Event newEvent = new Event
                {
                    Name = addEventViewModel.Name,
                    Description = addEventViewModel.Description,
                    ContactEmail = addEventViewModel.ContactEmail,
                    Category = theCategory
                };

                context.Events.Add(newEvent);
                context.SaveChanges();

                return Redirect("/Events");
            }

            return View(addEventViewModel);
            
        }

        public IActionResult Delete()
        {
            ViewBag.events = context.Events.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] eventIds)
        {
            foreach(int id in eventIds)
            {
                Event theEvent = context.Events.Find(id);
                context.Events.Remove(theEvent);
            }
            context.SaveChanges();
            return Redirect("/Events");
        }

        [HttpGet("/Events/Edit/{eventId?}")]
        public IActionResult Edit(int eventId)
        {
            ViewBag.evt = context.Events.Find(eventId);
            ViewBag.title = "Edit Event " + ViewBag.evt.Name + " (id = " + ViewBag.evt.Id + ")";
            return View();
        }

        [HttpPost("/Events/Edit")]
        public IActionResult SubmitEditEventForm(int eventId, string name, string description)
        {
            ViewBag.evt = context.Events.Find(eventId);
            ViewBag.evt.Name = name;
            ViewBag.evt.Description = description;

            return Redirect("/Events");
        }

        public IActionResult Detail(int id)
        {
            Event theEvent = context.Events
               .Include(e => e.Category)
               .Single(e => e.Id == id);

            List<EventTag> eventTags = context.EventTags
                .Where(et => et.EventId == id)
                .Include(et => et.Tag)
                .ToList();

            EventDetailViewModel viewModel = new EventDetailViewModel(theEvent, eventTags);
            return View(viewModel);
        }
    }
}

CodingEvents/Controllers/TagController.cs
using CodingEvents.Data;
using CodingEvents.Models;
using CodingEvents.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodingEvents.Controllers
{
    public class TagController : Controller
    {
        private EventDbContext context;
        public TagController(EventDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            List<Tag> tags = context.Tags.ToList();
            return View(tags);
        }

        public IActionResult Add()
        {
            Tag tag = new Tag();
            return View(tag);
        }

        [HttpPost]
        public IActionResult Add(Tag tag)
        {
            if (ModelState.IsValid)
            {
                context.Tags.Add(tag);
                context.SaveChanges();
                return Redirect("/Tag");
            }
            return View("Add", tag);
        }

        public IActionResult AddEvent(int id)
        {
            Event theEvent = context.Events.Find(id);
            List<Tag> possibleTags = context.Tags.ToList();

            AddEventTagViewModel addEventTagViewModel = new AddEventTagViewModel(theEvent, possibleTags);
            return View(addEventTagViewModel);
        }

        [HttpPost]
        public IActionResult AddEvent(AddEventTagViewModel addEventTagViewModel)
        {
            if (ModelState.IsValid)
            {
                int eventId = addEventTagViewModel.EventId;
                int tagId = addEventTagViewModel.TagId;

                List<EventTag> existingItems = context.EventTags
                    .Where(et => et.EventId == eventId)
                    .Where(et => et.TagId == tagId)
                    .ToList();

                if(existingItems.Count == 0)
                {
                    EventTag eventTag = new EventTag
                    {
                        EventId = eventId,
                        TagId = tagId
                    };

                    context.EventTags.Add(eventTag);
                    context.SaveChanges();
                }
                return Redirect("/Events/Detail/" + eventId);
            }

            return View(addEventTagViewModel);
        }

        public IActionResult Detail(int id)
        {
            List<EventTag> eventTags = context.EventTags
                .Where(et => et.TagId == id)
                .Include(et => et.Event)
                .Include(et => et.Tag)
                .ToList();

            return View(eventTags);
        }
    }
}

CodingEvents/Views/Events/Add.cshtml
@using CodingEvents.ViewModels;

@model AddEventViewModel;

<h1>Add Event</h1>
<form method="post">
    <div asp-controller="Events" asp-action="Add" class="form-group">
        <label asp-for="Name">Event Name: </label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description: </label>
        <input asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail">Contact Email: </label>
        <input asp-for="ContactEmail" />
        <span asp-validation-for="ContactEmail"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId">Event Types: </label>
            <select asp-for="CategoryId" asp-items="Model.Categories"></select>
    </div>
    <input type="submit" value="Add Event" />
</form>

CodingEvents/Views/Events/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Delete Events</h1>

<form method="post">
    @foreach(Event evt in ViewBag.events)
            {
                <div class="form-group">
                    <label>
                        <span>@evt.Name</span>
                        <input type="checkbox" name="eventIds" value="@evt.Id" />
                    </label>
                </div>
            }
    <input type="submit" value="Delete Selected Events" class="btn btn-danger"/>
</form>

CodingEvents/Views/Events/Detail.cshtml
@model CodingEvents.ViewModels.EventDetailViewModel

<h1>@Model.Name</h1>

<table class="table">
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
    <tr>
        <th>Contact Email</th>
        <td>@Model.ContactEmail</td>
    </tr>
    <tr>
        <th>Category</th>
        <td>@Model.CategoryName</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>@Model.TagText</td>
    </tr>

</table>

<a asp-controller="Tag" asp-action="AddEvent" asp-route-id="@Model.EventId">Add Tag</a>

CodingEvents/Views/Events/Edit.cshtml
<h1>Edit Event</h1>
<h5>@ViewBag.title</h5>
<form method="post" action="/events/edit">
    <input type="hidden" value="@ViewBag.evt.Id" name="eventId" />
    <label for="name">Event Name: </label>
    <input name="name" type="text" value="@ViewBag.evt.Name"/><br />
    <label for="description">Description: </label>
    <input name="description" type="text" value="@ViewBag.evt.Description"/><br />
    <input type="submit" value="Edit Event" />
</form>

CodingEvents/Views/Events/Index.cshtml
@using CodingEvents

@model List<Event>

<h1>Coding Events</h1>

<p>
    <a asp-controller="Events" asp-action="Add">Add Event</a>
</p>
<p>
    <a asp-controller="Events" asp-action="Delete">Delete Event</a>
</p>

@if(Model.Count == 0)
            {
                <p>No events yet.</p>
            }
            else
            {
                <table class="table">
                    <tr>
                        <th>ID</th>
                        <th>Event Name</th>
                        <th>Description</th>
                        <th>Contact Email</th>
                        <th>Category</th>
                    </tr>
                    @foreach (Event meeting in Model)
                    {
                        <tr>
                            <td>@meeting.Id</td>
                            <td><a asp-controller="Events" asp-action="Detail" asp-route-id=@meeting.Id>@meeting.Name</a></td>
                            <td>@meeting.Description</td>
                            <td>@meeting.ContactEmail</td>
                            <td>@meeting.Category.Name</td>
                            <td><a asp-controller="Events" asp-action="Edit" asp-route-eventId="@meeting.Id">Edit Event</a></td>
                        </tr>
                    }
                </table>
            }